# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: complyctl

before:
  hooks:
    - go mod tidy
    - go mod vendor
    #- go generate ./...

builds:
  - #
    id: complyctl
    binary: complyctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - "-X github.com/complytime/complyctl/internal/version.version={{ .Version }}"
      - "-X github.com/complytime/complyctl/internal/version.gitTreeState={{ .GitTreeState }}"
      - "-X github.com/complytime/complyctl/internal/version.commit={{ .Commit }}"
      - "-X github.com/complytime/complyctl/internal/version.buildDate={{ .Date }}"
    main: ./cmd/complyctl/
  - #
    id: openscap-plugin
    binary: openscap-plugin
    goos:
      - linux
    main: ./cmd/openscap-plugin/

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum # only need to sign checksums
    output: true
