sonar.projectKey=rh-psce_complyctl
sonar.organization=rh-psce

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=complyctl
#sonar.projectVersion=1.0

# Exclude vendored dependencies from analysis
sonar.exclusions=vendor/**

# Disable C/C++/Objective-C sensors (pure Go project)
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
