name: "Setup complyctl environment"
description: "Setup environment for complyctl running"

runs:
  using: composite
  steps:
    # Install dependency on fedora
    - name: Install dependency
      run: dnf install wget make scap-security-guide git -y
      shell: bash

    # Configure Git for safe directory
    - name: Configure Git for safe directory
      run: git config --global --add safe.directory /__w/complyctl/complyctl
      shell: bash
    
    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: './go.mod'

    # Build complyctl and setup complyctl
    - name: Build complyctl and setup complyctl
      run: sh tests/build_init_env.sh
      shell: bash
