name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  call_reusable_ci:
    name: Standardized CI
    uses: complytime/org-infra/.github/workflows/reusable_ci.yml@393ab96ded06d41472526fb46ebe7a7188c422d3 # v0.2.0
    permissions:
      contents: read
      issues: read
