name: unit-test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: './go.mod'

      # Step 3: Install Go dependencies (modules)
      - name: Install dependencies
        run: go mod tidy  # This ensures Go dependencies are up-to-date

      # Step 4: Run Go tests
      - name: Run unit tests
        run: go test -v $(go list ./... | grep -v /tests)
