name: unit-test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: './go.mod'

      # Step 3: Install Go dependencies (modules)
      - name: Install dependencies
        run: go mod tidy  # This ensures Go dependencies are up-to-date

      # Step 4: Run Go tests
      - name: Run unit tests
        run: go list ./... | grep -v /tests | xargs go test -v
